# Generated by Django 5.1.5 on 2025-02-23 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='company_id', verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='diamonds',
            field=models.IntegerField(default=0, verbose_name='Diamonds'),
        ),
        migrations.AddField(
            model_name='event',
            name='quota',
            field=models.IntegerField(default=10, verbose_name='Quota'),
        ),
    ]
