# Generated by Django 5.1.5 on 2025-02-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_company_event_diamonds_event_quota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hobby_type',
        ),
        migrations.AddField(
            model_name='event',
            name='hobbies',
            field=models.ManyToManyField(related_name='events', to='events.hobby'),
        ),
    ]
