# Generated by Django 5.1.5 on 2025-02-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_hobby_type_event_hobbies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='hobbies',
            new_name='hobby_type',
        ),
    ]
