# Generated by Django 5.1.5 on 2025-03-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_employee_diamonds'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='social_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='social_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
