# Generated by Django 5.1.5 on 2025-04-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_pointsaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('offline-outdoor', 'Offline - Outdoor'), ('offline-indoor', 'Offline - Indoor'), ('online', 'Online')], default='offline-indoor', max_length=15),
        ),
    ]
