# Generated by Django 5.1.5 on 2025-04-13 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_prize_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
