# Generated by Django 5.1.5 on 2025-04-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_organizernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organizernotification',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
    ]
