# Generated by Django 5.1.5 on 2025-04-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizernotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
