# Generated by Django 5.1.5 on 2025-02-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('company_id', models.CharField(max_length=100, unique=True, verbose_name='Company ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of Creation')),
            ],
        ),
    ]
