# Generated by Django 5.1.5 on 2025-02-09 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('nickname', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nickname')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('number', models.CharField(max_length=20, verbose_name='Number')),
                ('join_date', models.DateField(verbose_name='Join Date')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.company', verbose_name='Company ID')),
            ],
        ),
    ]
