# Generated by Django 5.1.5 on 2025-02-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_hobbies_event_hobby_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='hobby_type',
            new_name='hobbies',
        ),
    ]
