# Generated by Django 5.1.5 on 2025-02-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='diamonds',
            field=models.IntegerField(default=0, verbose_name='Diamonds'),
        ),
    ]
