# Generated by Django 5.1.5 on 2025-02-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_company_options_remove_company_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='company_profiles/'),
        ),
    ]
