# Generated by Django 5.1.5 on 2025-02-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_profile_picture_company_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='profile_image',
            new_name='profile_picture',
        ),
    ]
