# Generated by Django 5.1.5 on 2025-02-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_rename_profile_image_company_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profile_photo.png', null=True, upload_to='company_profiles/'),
        ),
    ]
