# Generated by Django 5.1.5 on 2025-03-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
