# Generated by Django 4.2.19 on 2025-04-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
    ]
