# Generated by Django 5.1.5 on 2025-04-06 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_event_latitude_remove_event_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, to_field='company_id', verbose_name='Company'),
        ),
        migrations.CreateModel(
            name='LiveGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Game Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Game Description')),
                ('max_points', models.PositiveIntegerField(default=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_games', to='events.event', verbose_name='Event')),
            ],
        ),
    ]
