# Generated by Django 5.1.5 on 2025-02-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_employee_date_of_birth_employee_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='organizer_profile_photos/', verbose_name='Organizer Profile Photo'),
        ),
    ]
