# Generated by Django 4.2.19 on 2025-02-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_company_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('hobby_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='hobby')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='hobbies_of_users',
            field=models.ManyToManyField(blank=True, to='events.hobby', verbose_name='Hobbies'),
        ),
    ]
