# Generated by Django 5.1.5 on 2025-02-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_company_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Hobby Name')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='employees', to='events.hobby'),
        ),
    ]
