# Generated by Django 5.1.5 on 2025-02-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_hobby_employee_hobbies'),
        ('events', '0020_hobby_employee_hobbies_of_users'),
    ]

    operations = [
    ]
