# Generated by Django 5.1.5 on 2025-02-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_merge_20250217_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hobbies_of_users',
        ),
    ]
