# Generated by Django 4.2.19 on 2025-04-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
